export const SET_CITY_INPUT = "SET_CITY_INPUT";

export const FETCH_WEATHER_DATA_PENDING = "FETCH_WEATHER_DATA_PENDING";
export const FETCH_WEATHER_DATA_SUCCESS = "FETCH_WEATHER_DATA_SUCCESS";
export const FETCH_WEATHER_DATA_FAILED = "FETCH_WEATHER_DATA_FAILED";
